#!/bin/bash
set -euo pipefail

# Updates appcast.xml with a new release item.
# Reads the item XML from .build-app/appcast-item.xml (generated by build.sh)

BUILD_DIR="$(pwd)/.build-app"
APPCAST_ITEM="${BUILD_DIR}/appcast-item.xml"
APPCAST="appcast.xml"

if [ ! -f "${APPCAST_ITEM}" ]; then
    echo "Error: ${APPCAST_ITEM} not found. Run build.sh with SPARKLE_SIGNING_KEY first."
    exit 1
fi

if [ ! -f "${APPCAST}" ]; then
    # Create new appcast with the item
    ITEM_CONTENT=$(cat "${APPCAST_ITEM}")
    cat > "${APPCAST}" <<XMLEOF
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:dc="http://purl.org/dc/elements/1.1/">
    <channel>
        <title>Beads</title>
        <description>Beads app updates</description>
        <language>en</language>
${ITEM_CONTENT}
    </channel>
</rss>
XMLEOF
else
    # Insert new item before </channel> using python for reliable multiline handling
    python3 -c "
import sys
with open('${APPCAST}', 'r') as f:
    content = f.read()
with open('${APPCAST_ITEM}', 'r') as f:
    item = f.read()
content = content.replace('    </channel>', item + '\n    </channel>')
with open('${APPCAST}', 'w') as f:
    f.write(content)
"
fi

echo "==> Updated ${APPCAST}"
